# AndroidX
android.useAndroidX=true
# Kotlin code style
kotlin.code.style=official
# Enables namespacing of each library's R class
android.nonTransitiveRClass=true
# AGP 9 dsl modes
android.newDsl=false
android.disallowKotlinSourceSets=false
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
